spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learniverse?useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
